version: "2"
services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html/project
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/var/log/nginx
    networks:
      - webnet
    links:
      - php-fpm:php
  php-fpm:
    image: php:7.2-fpm
    volumes:
      - ./www:/var/www/html/project
    networks:
      - webnet
networks:
  webnet: